# -*- coding: utf-8 -*-
"""Linear_reg_Ass-.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IJaUviFvs1yx-DpKgpugyKaDW1kfQNGK
"""

from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt
x=np.array([1400, 1600, 1700, 1875, 1100, 1550, 2350, 2450, 1425, 1700]).reshape(-1,1)
y=np.array([245, 312, 279, 308, 199, 219, 405, 324, 319, 255])
x
y

# step 1
model = LinearRegression().fit(x,y)

# step 2
r_sq = model.score(x,y)
r_sq

# step 3
b0 = model.intercept_ # intercept
b1 = model.coef_ # slope
print(f"Intercerpt= {b0} and Slope = {b1}")

# step 4
Y = b0 + b1*3000

# step 5
#plotting the actual points as scatter plot
plt.scatter(x, y)

#plotting the predicted line
y_predicted = b0 + b1*x
plt.plot(x, y_predicted)
#putting labels
plt.xlabel('Area (square feet)')
plt.ylabel('House Price (in $1000s)')