# -*- coding: utf-8 -*-
"""multipleLinearReg.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-tQufePNt3KjPRNGFuNBmUnuK19HTSvb
"""

from sklearn.linear_model import LinearRegression
import numpy as np
import matplotlib.pyplot as plt

x = [[2.75,5.3], [2.5,5.3], [2.5,5.3], [2.5,5.3], [2.5,5.4], [2.5,5.6], [2.5,5.5] ,[2.25,5.5], [2.25,5.5] ,[2.25,5.6] ,[2,5.7], [2,5.9], [2,6], [1.75,5.9], [1.75,5.8], [1.75,6.1], [1.75,6.2], [1.75,6.1], [1.75,6.1], [1.75,6.1], [1.75,5.9], [1.75,6.2] ,[1.75,6.2], [1.75,6.1]]
y = [1464, 1394, 1357, 1293, 1256, 1254, 1234, 1195, 1159, 1167, 1130, 1075, 1047, 965, 943, 958, 971, 949, 884, 866, 876, 822, 704, 719]
x, y = np.array(x), np.array(y)
x
y

model = LinearRegression().fit(x,y)

slp_coff = model.coef_
b0 = model.intercept_
b1 = slp_coff[0]
b2 = slp_coff[1]
print(f"b0 = {b0} , b1 = {b1} and b2 = {b2}")
Y = b0 + b1*1.5 + b2*6.8
print(f"Y = {Y}")