# -*- coding: utf-8 -*-
"""PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mET9kY0rKWYc9pNf2cawwC4b8E8KsJhn
"""

from sklearn.datasets import load_digits
import pandas as pd
import numpy as np

data = load_digits()
print(data)

df = pd.DataFrame(data['data'])
df

from sklearn.preprocessing import StandardScaler
scalar = StandardScaler()

# fitting
scalar.fit(df)
scaled_data = scalar.transform(df)

# Importing PCA
from sklearn.decomposition import PCA
pca = PCA(n_components = 30)
pca.fit(scaled_data)
x_pca = pca.transform(scaled_data)
x_pca.shape
x_pca